### ISSUE TITLE
Can you upload training and val datasets to github?

### ISSUE THREAD

**Issue by ulanbator** [yijingru/KG_Instance_Segmentation#2]
I want to run this project,but I don't have datasets of the project,I will appreciate it if you can upload the datasets to the github.

**Comment by yijingru** [comment]
I downloaded the kaggle data from https://www.kaggle.com/c/data-science-bowl-2018/data. You can also download the stage1_train.zip and split it into train, test and validation datasets, the ratio is 6:2:2. It should have similar results.

**Comment by ulanbator** [comment]
Thank you so much.
