### ISSUE TITLE
Plant dataset

### ISSUE THREAD

**Issue by Ghulam111** [yijingru/KG_Instance_Segmentation#3]
what is the plant dataset that you used in the file `dataset_plant.py` ?

**Comment by yijingru** [comment]
Hi, it's the Plant Phenotyping dataset used in my other paper "Object-Guided Instance Segmentation for Biological Images".

**Comment by JoneColdplay** [comment]
Hello, when is the code of "object guided instance segmentation for biological images" open source

**Comment by yijingru** [comment]
It is my intern work so it is under the approval process of the company. When it's approved I will release the code immediately.
